---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r echo =TRUE}
data <- read.csv("activity.csv")
str(data) ##loading data and showing structure
```

## What is mean total number of steps taken per day?

```{r echo =TRUE}

steps <- aggregate(data$steps, list(data = data$date), sum)
hist(steps$x, 
     breaks = 30,
     main = "Distribution of Total Steps per Day, 10/1/12 - 11/30/12",
     xlab = "# of Steps",
     ylab = "Frequency")

mean1 <- mean(steps$x, na.rm = TRUE) ## Mean total steps per day
mean1
median1 <- median(steps$x, na.rm = TRUE) ## Median total steps per day
median1

```
    
## What is the average daily activity pattern?

```{r echo =TRUE}

interval <- aggregate(data$steps, list(data = data$interval), mean, na.rm = TRUE)
plot(interval$data, interval$x, type = "l",
     main = "Average Daily Activity Pattern",
     xlab = "Time of Day",
     ylab = "Average Steps Taken")

maxinterval <- interval[which.max(interval[,2]),]
maxinterval[,1]    ## 5 minute time interval with the most average steps

```


## Imputing missing values

```{r echo =TRUE}

sum(is.na(data$steps)) ## Total number of rows with missing data

## Logic for imputing missing values: if step count for a given row is NA, put in the mean step count for that 5-minute interval. To do this, iterate over each row of the dataset.

for (i in 1:length(data$steps)) {                                
    if (is.na(data[i,1])) {
       a <- data[i,3] ##find the interval value for the missing row
       data[i,1] = 10
       }
}
 
data2 <- data ## new dataset with filled in missing values
data <- read.csv("activity.csv") ## reset original dataframe

steps2 <- aggregate(data2$steps, list(data2 = data2$date), sum)
hist(steps2$x, 
     breaks = 30,
     main = "Distribution of Total Steps per Day, NAs imputed",
     xlab = "# of Steps",
     ylab = "Frequency")

mean2 <- mean(steps2$x, na.rm = TRUE) ## New mean total steps per day
mean2
median2 <- median(steps2$x, na.rm = TRUE) ## New median total steps per day
median2

meandifference <- mean1 - mean2
meandifference ## what is the difference between the means from the first and second data sets?

mediandifference <- median1 - median2
mediandifference ## what is the difference between the medians from the first and second data sets?

```

## Are there differences in activity patterns between weekdays and weekends?

```{r echo =TRUE}
data2$weektype <- weekdays(as.Date(data2$date)) ## add column for weekday vs. weekend
    
```
